### PR TITLE
minor code refactoring

### PR DESCRIPTION
**Pull request by itzvinoth**
minor changes with es6 classes as just syntactic sugar.

### CODE REVIEW

**Comment by knadh** [comment]
Variables from [line 9](/mevinoth/wordpluck/blob/b7ec46daafbf505513bf4f3759a0ce0307cc2a2f/js/main.js#L9) to [line 58](https://github.com/mevinoth/wordpluck/blob/b7ec46daafbf505513bf4f3759a0ce0307cc2a2f/js/main.js#L58) are in the global scope. They should also be inside the class.

**Comment by knadh** [comment]
```
		this.RADIUS = 30
		this.BORDER = 4
		this.FONT_SIZE = 36
		this.FPS = 60
		this.SCORE_LETTER = 10
		this.WORDS_PER_LEVEL = 3
```

^ Since these are constants, isn't ES6 `const` more appropriate? Everything else looks fine. Thanks!

**Comment by itzvinoth** [comment]
> ```
> 		this.RADIUS = 30
> 		this.BORDER = 4
> 		this.FONT_SIZE = 36
> 		this.FPS = 60
> 		this.SCORE_LETTER = 10
> 		this.WORDS_PER_LEVEL = 3
> ```
> 
> ^ Since these are constants, isn't ES6 `const` more appropriate? Everything else looks fine. Thanks!

yeah but once es6 `const` assigned with value it becomes immutable, and can't use `const` inside es6 class contructor.

**Comment by knadh** [comment]
Ah yes. Just realised that some of these are being mutated.

**Pull request merged**
